apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: nodejs-dev-demo-staging

images:
- digest: sha256:20de2783b76ca549e805d60f5396c62446a6e0df78d554ff5201d535742a4eb8
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: quay-registry-quay-quay.apps.rosa.sb1237-rosa.b20c.p3.openshiftapps.com/skitamura-quay-org/nodejs-dev-demo/nodejs-dev-demo
